#! /bin/bash


echo 'setting up clean mushroom folder...'

echo $1
mkdir $1
cd $1

mkdir .mushroom
cp -R /Users/matthewbradbury/Dropbox/development/Dapps/mushroom/.mushroom/ ./.mushroom
cp /Users/matthewbradbury/Dropbox/development/Dapps/mushroom/.mushroom_config.js .
cp /Users/matthewbradbury/Dropbox/development/Dapps/mushroom/mushroom.js .
cp /Users/matthewbradbury/Dropbox/development/Dapps/mushroom/package.json .
cp /Users/matthewbradbury/Dropbox/development/Dapps/mushroom/.gitignore .


mkdir config

cp -R /Users/matthewbradbury/Dropbox/development/Dapps/mushroom/config/ ./config

mkdir sources

cp -R /Users/matthewbradbury/Dropbox/development/Dapps/mushroom/sources/ ./sources

mkdir output

cp -R /Users/matthewbradbury/Dropbox/development/Dapps/mushroom/output/ ./output


npm install